#!/bin/sh

ROOT=$1
BUILD=$2

LANG=C BUILD_LEVEL=testing BUILD_NUMBER=0 CHECKOUT_DIR=$ROOT LTIB_BUILD=$BUILD/ltib-with-encadis-merge LTIB_ROOT=$CHECKOUT_DIR/com.freescale.ltib2 LTIB_ROOTFS=$CHECKOUT_DIR/com.freescale.ltib2/rootfs JAVA_HOME=/usr/lib/jvm/j2sdk1.4.2_17 ./ltib $3 $4 $5 $6 $7 $8 $9

