
.phony=install

install:
	sudo dd if=$(MBRIMAGE) of=$(TARGET)
	sleep 1
	sudo mkfs.ext3 $(TARGET)1
	sleep 1
	sudo mount -t ext3 $(TARGET)1 /mnt/usbflash
	sleep 1
	sudo tar cvf - . --preserve | (cd /mnt/usbflash; sudo tar xvf - --preserve)
	sync
	sudo umount /mnt/usbflash

