
.phony=all

KERNEL_DIRECTORY=$(CHECKOUT_DIR)/com.freescale.ltib2/rpm/BUILD/linux-2.6.19.2

all:
	/usr/bin/python $(CHECKOUT_DIR)/scripts/merge_kernel.py -o $(KERNEL_DIRECTORY)
#	cp com.freescale.ltib2/bugpm.c com.freescale.ltib2/rpm/BUILD/linux-2.6.19.2/drivers/mxc/bugpm/bugpm.c
#	cp com.freescale.ltib2/bugpm.h com.freescale.ltib2/rpm/BUILD/linux-2.6.19.2/include/linux/bugpm.h

