/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_buglabs_bug_jni_camera_CameraControl */

#ifndef _Included_com_buglabs_bug_jni_camera_CameraControl
#define _Included_com_buglabs_bug_jni_camera_CameraControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_buglabs_bug_jni_camera_CameraControl
 * Method:    ioctl_BMI_CAM_FLASH_HIGH_BEAM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_camera_CameraControl_ioctl_1BMI_1CAM_1FLASH_1HIGH_1BEAM
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_camera_CameraControl
 * Method:    ioctl_BMI_CAM_FLASH_LOW_BEAM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_camera_CameraControl_ioctl_1BMI_1CAM_1FLASH_1LOW_1BEAM
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_camera_CameraControl
 * Method:    ioctl_BMI_CAM_FLASH_LED_OFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_camera_CameraControl_ioctl_1BMI_1CAM_1FLASH_1LED_1OFF
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_camera_CameraControl
 * Method:    ioctl_BMI_CAM_FLASH_LED_ON
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_camera_CameraControl_ioctl_1BMI_1CAM_1FLASH_1LED_1ON
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_camera_CameraControl
 * Method:    ioctl_BMI_CAM_RED_LED_OFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_camera_CameraControl_ioctl_1BMI_1CAM_1RED_1LED_1OFF
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_camera_CameraControl
 * Method:    ioctl_BMI_CAM_RED_LED_ON
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_camera_CameraControl_ioctl_1BMI_1CAM_1RED_1LED_1ON
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_camera_CameraControl
 * Method:    ioctl_BMI_CAM_GREEN_LED_OFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_camera_CameraControl_ioctl_1BMI_1CAM_1GREEN_1LED_1OFF
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_camera_CameraControl
 * Method:    ioctl_BMI_CAM_GREEN_LED_ON
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_camera_CameraControl_ioctl_1BMI_1CAM_1GREEN_1LED_1ON
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_camera_CameraControl
 * Method:    ioctl_BMI_CAM_SELECT
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_camera_CameraControl_ioctl_1BMI_1CAM_1SELECT
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_camera_CameraControl
 * Method:    ioctl_BMI_CAM_GET_SELECTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_camera_CameraControl_ioctl_1BMI_1CAM_1GET_1SELECTED
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
