/*******************************************************************************
 * Copyright (c) 2008, 2009 Bug Labs, Inc.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *    - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *    - Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *    - Neither the name of Bug Labs, Inc. nor the names of its contributors may be
 *      used to endorse or promote products derived from this software without
 *      specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_buglabs_bug_jni_lcd_LCDControl */

#ifndef _Included_com_buglabs_bug_jni_lcd_LCDControl
#define _Included_com_buglabs_bug_jni_lcd_LCDControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_RLEDOFF
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1RLEDOFF
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_RLEDON
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1RLEDON
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_GLEDOFF
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1GLEDOFF
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_GLEDON
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1GLEDON
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_VSYNC_DIS
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1VSYNC_1DIS
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_VSYNC_EN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1VSYNC_1EN
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_EN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1EN
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_DIS
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1DIS
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_SER_EN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1SER_1EN
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_SER_DIS
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1SER_1DIS
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_SETRST
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1SETRST
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_CLRRST
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1CLRRST
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_SET_BL
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1SET_1BL
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_GETSTAT
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1GETSTAT
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_ACTIVATE
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1ACTIVATE
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_DEACTIVATE
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1DEACTIVATE
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_SUSPEND
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1SUSPEND
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_RESUME
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1RESUME
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
