/*******************************************************************************
 * Copyright (c) 2008, 2009 Bug Labs, Inc.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *    - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *    - Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *    - Neither the name of Bug Labs, Inc. nor the names of its contributors may be
 *      used to endorse or promote products derived from this software without
 *      specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_buglabs_bug_jni_gps_GPS */

#ifndef _Included_com_buglabs_bug_jni_gps_GPS
#define _Included_com_buglabs_bug_jni_gps_GPS
#ifdef __cplusplus
extern "C" {
#endif
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_RLEDOFF
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_RLEDOFF 1L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_RLEDON
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_RLEDON 2L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_GLEDOFF
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_GLEDOFF 3L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_GLEDON
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_GLEDON 4L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_SETBOOT
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_SETBOOT 5L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_CLRBOOT
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_CLRBOOT 6L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_SETWAKE
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_SETWAKE 7L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_CLRWAKE
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_CLRWAKE 8L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_SETRST
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_SETRST 10L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_CLRRST
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_CLRRST 11L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_ACTIVE_ANT
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_ACTIVE_ANT 12L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_PASSIVE_ANT
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_PASSIVE_ANT 13L
/*
 * Class:     com_buglabs_bug_jni_gps_GPS
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_gps_GPS_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
