/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_buglabs_bug_jni_gps_GPSControl */

#ifndef _Included_com_buglabs_bug_jni_gps_GPSControl
#define _Included_com_buglabs_bug_jni_gps_GPSControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_buglabs_bug_jni_gps_GPSControl
 * Method:    ioctl_BMI_GPS_RLEDOFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_gps_GPSControl_ioctl_1BMI_1GPS_1RLEDOFF
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_gps_GPSControl
 * Method:    ioctl_BMI_GPS_RLEDON
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_gps_GPSControl_ioctl_1BMI_1GPS_1RLEDON
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_gps_GPSControl
 * Method:    ioctl_BMI_GPS_GLEDOFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_gps_GPSControl_ioctl_1BMI_1GPS_1GLEDOFF
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_gps_GPSControl
 * Method:    ioctl_BMI_GPS_GLEDON
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_gps_GPSControl_ioctl_1BMI_1GPS_1GLEDON
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_gps_GPSControl
 * Method:    ioctl_BMI_GPS_GETSTAT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_gps_GPSControl_ioctl_1BMI_1GPS_1GETSTAT
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_gps_GPSControl
 * Method:    ioctl_BMI_GPS_SETRST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_gps_GPSControl_ioctl_1BMI_1GPS_1SETRST
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_gps_GPSControl
 * Method:    ioctl_BMI_GPS_CLRRST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_gps_GPSControl_ioctl_1BMI_1GPS_1CLRRST
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_gps_GPSControl
 * Method:    ioctl_BMI_GPS_ACTIVE_ANT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_gps_GPSControl_ioctl_1BMI_1GPS_1ACTIVE_1ANT
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_gps_GPSControl
 * Method:    ioctl_BMI_GPS_PASSIVE_ANT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_gps_GPSControl_ioctl_1BMI_1GPS_1PASSIVE_1ANT
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
