/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_buglabs_bug_jni_common_CharDevice */

#ifndef _Included_com_buglabs_bug_jni_common_CharDevice
#define _Included_com_buglabs_bug_jni_common_CharDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_buglabs_bug_jni_common_CharDevice
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_common_CharDevice_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_buglabs_bug_jni_common_CharDevice
 * Method:    getline
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_buglabs_bug_jni_common_CharDevice_getline
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_common_CharDevice
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_common_CharDevice_read
  (JNIEnv *, jobject);

/*
 * Class:     com_buglabs_bug_jni_common_CharDevice
 * Method:    readBytes
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_common_CharDevice_readBytes
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_buglabs_bug_jni_common_CharDevice
 * Method:    lseek
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_buglabs_bug_jni_common_CharDevice_lseek
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_buglabs_bug_jni_common_CharDevice
 * Method:    write
 * Signature: ([BJ)J
 */
JNIEXPORT jlong JNICALL Java_com_buglabs_bug_jni_common_CharDevice_write
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_buglabs_bug_jni_common_CharDevice
 * Method:    ioctl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_common_CharDevice_ioctl
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_common_CharDevice
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_common_CharDevice_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
