/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_buglabs_bug_jni_gps_GPS */

#ifndef _Included_com_buglabs_bug_jni_gps_GPS
#define _Included_com_buglabs_bug_jni_gps_GPS
#ifdef __cplusplus
extern "C" {
#endif
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_RLEDOFF
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_RLEDOFF 1L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_RLEDON
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_RLEDON 2L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_GLEDOFF
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_GLEDOFF 3L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_GLEDON
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_GLEDON 4L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_SETBOOT
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_SETBOOT 5L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_CLRBOOT
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_CLRBOOT 6L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_SETWAKE
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_SETWAKE 7L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_CLRWAKE
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_CLRWAKE 8L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_SETRST
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_SETRST 10L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_CLRRST
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_CLRRST 11L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_ACTIVE_ANT
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_ACTIVE_ANT 12L
#undef com_buglabs_bug_jni_gps_GPS_BMI_GPS_PASSIVE_ANT
#define com_buglabs_bug_jni_gps_GPS_BMI_GPS_PASSIVE_ANT 13L
/*
 * Class:     com_buglabs_bug_jni_gps_GPS
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_gps_GPS_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
