/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_buglabs_bug_jni_lcd_LCDControl */

#ifndef _Included_com_buglabs_bug_jni_lcd_LCDControl
#define _Included_com_buglabs_bug_jni_lcd_LCDControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_RLEDOFF
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1RLEDOFF
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_RLEDON
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1RLEDON
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_GLEDOFF
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1GLEDOFF
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_GLEDON
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1GLEDON
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_VSYNC_DIS
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1VSYNC_1DIS
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_VSYNC_EN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1VSYNC_1EN
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_EN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1EN
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_DIS
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1DIS
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_SER_EN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1SER_1EN
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_SER_DIS
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1SER_1DIS
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_SETRST
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1SETRST
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_CLRRST
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1CLRRST
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_SET_BL
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1SET_1BL
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_GETSTAT
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1GETSTAT
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_ACTIVATE
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1ACTIVATE
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_DEACTIVATE
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1DEACTIVATE
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_SUSPEND
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1SUSPEND
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_buglabs_bug_jni_lcd_LCDControl
 * Method:    ioctl_BMI_LCD_RESUME
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_buglabs_bug_jni_lcd_LCDControl_ioctl_1BMI_1LCD_1RESUME
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
