<html>
  <head>
    <title>BUGdash</title>
   	<link rel="stylesheet" href="${_stylesheetRoot}/global.css" type="text/css" />
    <script type="text/javascript" src="${_javascriptRoot}/jquery.tools.min.js"></script>
    <script type="text/javascript" src="${_javascriptRoot}/application.js"></script> 
    <style>
    	#nav {padding: 10px }
    	#nav h4 {background-color:#eee; padding: 4px 7px;}
    	#nav * {font-size: 13px; }
    </style>
  </head>
  <body>
  <div id="content">