/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cx_ath_matthew_cgi_CGI */

#ifndef _Included_cx_ath_matthew_cgi_CGI
#define _Included_cx_ath_matthew_cgi_CGI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cx_ath_matthew_cgi_CGI
 * Method:    getenv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cx_ath_matthew_cgi_CGI_getenv
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cx_ath_matthew_cgi_CGI
 * Method:    getfullenv
 * Signature: (Ljava/lang/Class;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_cx_ath_matthew_cgi_CGI_getfullenv
  (JNIEnv *, jobject, jclass);

/*
 * Class:     cx_ath_matthew_cgi_CGI
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cx_ath_matthew_cgi_CGI_setenv
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
